SekenWeb/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('berita/', include('berita.urls')),
]

berita/urls.py
from django.urls import path

from . import views

app_name = 'berita'

urlpatterns = [
    path('', views.home, name='home'),
    path('isiberita/', views.isiberita, name='isiberita'),
    path('<int:id>/', views.detail, name='detail'),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('signup/', views.registerUser, name='register'),
    path('login/', views.loginUser, name='login'),
    path('logout/', views.logoutUser, name='logout'),
]

berita/models.py
from django.db import models
import datetime

# Create your models here.
class Berita(models.Model):
    date = models.DateField(blank=True, null=True)
    time = models.TimeField(blank=True, null=True)
    name = models.CharField(max_length=100)
    judul = models.CharField(max_length=200)
    # gambar = models.ImageField(blank=True, null=True)
    isi = models.TextField()
    url = models.CharField(max_length=500)

main/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

GENDER = [
    ('Male', 'Male'),
    ('Female', 'Female'),
]

class TambahanUserModel(User):
    image_url = models.URLField(max_length = 100, blank = True, null = True)
    gender = models.CharField(max_length=20, choices=GENDER, default="Male")
    job = models.CharField(max_length = 50, null = True)
    social_media = models.CharField(max_length = 50)

berita/forms.py
from django import forms
from .models import Berita
import datetime

class BeritaForm(forms.ModelForm):
    class Meta:
        model = Berita
        fields = '__all__'

        widgets = {
            'date' : forms.DateInput(attrs={'class': 'form-control',
                                        'type' : 'date'}),
            'time' : forms.TimeInput(attrs={'class': 'form-control',
                                        'type' : 'time'}),

            'name' : forms.TextInput(attrs={'class': 'form-control',
                                        'type' : 'text',
                                        'placeholder' : 'Nama Anda'}),
            'judul' : forms.TextInput(attrs={'class' : 'form-control',
                                        'type' : 'text',
                                        'placeholder' : 'Judul berita'}),
            'isi' : forms.Textarea(attrs={'class' : 'form-control',
                                        'type' : 'text',
                                        'placeholder' : 'Berita Anda'}),                            
            'url' : forms.TextInput(attrs={'class' : 'form-control',
                                        'type' : 'text',
                                        'placeholder' : 'URL (example: www.google.com)'}),
        }

main/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from main.models import TambahanUserModel
from django import forms

class BuatUserForm(UserCreationForm):
    password1 = forms.CharField(
            widget=forms.TextInput(attrs = {
            'placeholder': 'Password',
            'type' : 'password',
            }))
        
    password2 = forms.CharField(
            widget=forms.TextInput(attrs = {
            'placeholder': 'Re-enter Password',
            'type' : 'password',
            }))
        
    image_url = forms.URLField(
            required = False, widget=forms.URLInput(attrs = {
            'type' : 'url', 'placeholder' : 'Profile Picture URL',
            }))

    class Meta:
        model = TambahanUserModel
        fields = ['username', 'first_name', 'password1', 'password2', 'image_url', 'gender', 'social_media']

        widgets = {
            'username' : forms.TextInput(attrs={'class' : 'form-control',
                                        'type' : 'text',
                                        'placeholder' : 'Username'}),
                                        
            'first_name' : forms.TextInput(attrs={'class' : 'form-control',
                                        'type' : 'text',
                                        'placeholder' : 'Your name'}),

            'gender' : forms.Select(attrs = {'class' : 'form-control',
                                            'type' : 'option'}),
            
            'social_media' : forms.TextInput(attrs={'class' : 'form-control',
                                        'type' : 'text',
                                        'placeholder' : 'Social Media. e.g. @abcd (ig)'})}
    

berita/views.py
from django.shortcuts import render, redirect
from .forms import BeritaForm
from .models import Berita

# Create your views here.
def isiberita(request):
    form = BeritaForm()

    if request.method == "POST":
        form = BeritaForm(request.POST)
        if form.is_valid():
            post = form.save(commit=True)
            post.save()
            return redirect('/berita/')
    else:
        form = BeritaForm()

    return render(request, 'isiberita.html', {'form' : form})

def home(request):
    daftar = Berita.objects.all()
    context = { 'obj' : daftar }
    return render(request, 'berita.html', context)

def detail(request, id):
    obj = Berita.objects.get(id=id)
    context = { "obj" : obj }
    return render(request, 'detail.html', context)

main/views.py
from django.shortcuts import render, redirect
from main.forms import BuatUserForm
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from main.models import TambahanUserModel

def home(request):
    if request.user.is_authenticated:
        return render(request, 'main/home.html')
    else:
        return HttpResponseRedirect('/login/')

def registerUser(request):
    form = BuatUserForm()
    
    if request.method == 'POST':
        form = BuatUserForm(request.POST)
        
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(request, username = username, password = password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect('/login/')
                
        else:
            messages.info(request, 'Your data is invalid')

    response = {'form':form}
    return render(request, 'main/register.html', response)

def loginUser(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username = username, password = password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect('/')
        else:
            messages.info(request, 'Username or password is incorrect')
    
    return render(request, 'main/login.html')

def logoutUser(request):
    logout(request)
    return HttpResponseRedirect('/')

berita/templates/berita.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Berita</title>
{% comment %} <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script> {% endcomment %}
<style>
    .container{
        background-color: black;
        color: white;
        padding: 165px;
    }
    .container h1{
        text-align: center;
    }
    .dari{
        margin-bottom: 20px;
        font-size: 14px;
    }
    .card{
        background-color: rgb(66, 0, 0);
        color: white;
        margin: 40px 0px;
        padding: 20px;
        border-radius: 10px;
    }
    .tambah{
        padding: 10px 20px;
        border-color: rgb(167, 0, 0);
        border-style: solid;
        border-radius: 7px;
        color: white;
        text-decoration: none;
    }
    .liatdetail{
        color: white;
        text-decoration: none;
    }
    .liatdetail:hover{
        color: rgb(255, 167, 167);
        transition: 0.5s;
    }
</style>
{% endblock meta %}
{% block content %}
<div class="overlay" style="font-size: 8rem;">
    <div class="overlay-3"><i class='fas fa-virus'></i></div>
</div>
<div class="container">
    <h1>Berita tentang Covid-19</h1>
    {% for daftar in obj %}
        <div class="card">
            <div class="dari">
                <p>{{ daftar.date }} {{ daftar.time }}</p>
                <p><span style="color: rgb(255, 167, 167);">Dari: </span> {{ daftar.name }}</p>
            </div>
            <h2><a class="liatdetail" href="{% url 'berita:detail' id=daftar.id %}">{{ daftar.judul }}</a></h1>
            <!-- <p>{{ daftar.isi }}</p><br>
            <p><span style="color: rgb(255, 167, 167);">Sumber: </span> {{ daftar.url }}</p> -->
        </div>
    {% endfor %}
    <br><br>
    <a class="tambah" href="{% url 'berita:isiberita' %}">Tambah Berita</a>
</div>
{% endblock content %}

berita/templates/detail.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Berita</title>
<!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script> -->
<style>
    .container{
        background-color: black;
        color: white;
        padding: 165px;
    }
    .dari{
        margin-bottom: 30px;
        font-size: 16px;
    }
    .isi h1{
        font-size: 40px;
    }
    .isi p{
        font-size: 18px;
    }
    .back{
        padding: 10px 20px;
        border-color: rgb(167, 0, 0);
        border-style: solid;
        border-radius: 7px;
        color: white;
        text-decoration: none;
    }
    .span{
        color: rgb(255, 167, 167);
    }
</style>
{% endblock meta %}

{% block content %}
    <div class="overlay" style="font-size: 8rem;">
        <div class="overlay-5"><i class='fas fa-virus'></i></div>
    </div>
    <div class="container">
    {% if obj %}
        <div class="dari">
            <p>{{ obj.date }} {{ obj.time }}</p>
            <p><span class="span">Dari: </span> {{ obj.name }}</p>
        </div>
        <div class="isi">
            <h1>{{ obj.judul }}</h1><br><br>
            <p>{{ obj.isi }}</p><br><br><br>
            <p><span class="span">Sumber: </span> {{ obj.url }}</p>
        </div>
    {% endif %}
    <br><br>
    <a class="back" href="{% url 'berita:home' %}">Kembali</a>
    </div>
{% endblock content %}

berita/templates/isiberita.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Isi Berita</title>
{% comment %} <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script> {% endcomment %}
<style>
    .container{
        padding: 165px 0px;
        background-color: black;
        color: white;
    }
    .container h1{
        text-align: center;
    }
    span{
        font-weight: bolder;
        font-size: 20px;
        line-height: 35px;
    }
    form{
        padding: 50px 100px;
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
    }
    input, textarea{
        background-color: rgb(209, 209, 209);
        padding: 15px 10px;
        border-radius: 10px;
        border-style: none;
        width: 500px;
        margin-bottom: 30px;
    }
    .button{
        background-color: transparent;
        padding: 10px 20px;
        width: 100px;
        font-size: 18px;
        border-color: rgb(167, 0, 0);
        border-style: solid;
        border-radius: 7px;
        color: white;
        text-decoration: none;
    }
</style>
{% endblock meta %}
{% block content %}
<div class="overlay" style="font-size: 8rem;">
    <div class="overlay-3"><i class='fas fa-virus'></i></div>
    <div class="overlay-6"><i class='fas fa-virus'></i></div>
</div>
<div class="container">
    <h1>Tambah Berita</h1>
    <form method="POST">
        <p><span style="color: rgb(167, 0, 0);">Tanggal</span></p>
        {{ form.date }}
        <p><span style="color: rgb(167, 0, 0);">Waktu</span></p>
        {{ form.time }}
        <p><span style="color: rgb(167, 0, 0);">Nama</span></p>
        {{ form.name }}
        <p><span style="color: rgb(167, 0, 0);">Judul</span></p>
        {{ form.judul }}
        <!-- <p><span style="color: rgb(167, 0, 0);">Gambar</span></p>
        {{ form.gambar }} -->
        <p><span style="color: rgb(167, 0, 0);">Berita</span></p>
        {{ form.isi }}
        <p><span style="color: rgb(167, 0, 0);">Sumber</span></p>
        {{ form.url }}
        {% csrf_token %}
        <br>
        <input class="button" type="submit" value="Submit">
    </form>    
</div>
{% endblock content %}

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Home</title>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
{% endblock meta %}

{% block content %}
<div class="overlay" style="font-size: 8rem;">
    <div class="overlay-3"><i class='fas fa-virus'></i></div>
    <div class="overlay-4"><i class='fas fa-virus'></i></div>
</div>
<div class="welcome">
  <div class="welc">
      <div class="destop">
          <div class="overlay">
              <div class="overlay-1">BOUVID</div>
              <div class="overlay-2">COVID</div>
          </div>
      </div>
      <h2>Hi, {{ user.first_name }}</h2>
      <h1>Welcome to <a class="logo2" href="home.html">BOUVID</a>.</h1><br>
      <p>Pandemi Covid-19 masih terjadi hingga saat ini sehingga menghambat aktivitas kita. Untuk itu, marilah kita berjuang dalam mengatasi pandemi ini demi kehidupan yang lebih baik. <a style="color: rgb(167, 0, 0);">#StaySafe #StayAtHome</a></p><br><br>
      <a class="klik" href="{% url 'berita:home' %}">Lihat Berita</a>
  </div>
</div>
<div class="what">
  <h1 style="padding-top: 50px;">What is <a style="color: rgb(167, 0, 0); font-size: 60px;">Covid-19</a> ?</h1><br>
  <p class="anda">Kenali dulu yuk tentang Covid-19.</p>
  <div class="row">
      <div class="isiwhat">
          <img src="https://cdn.pixabay.com/photo/2020/05/22/19/54/corona-5206917_960_720.png">
      </div>
      <div class="isiwhat">
          <p>Covid-19 merupakan suatu penyakit yang disebabkan oleh virus dari golongan coronavirus, yaitu SARS-CoV-2 atau lebih kita kenal sebagai virus Corona. Biasanya, orang yang terkena penyakit ini akan mengalami gangguan pernapasan, dimulai dari gejala ringan seperti flu, hingga infeksi paru-paru.</p>
          <p>Kasus Covid-19 pertama kali ditemukan di Kota Wuhan, Tiongkok pada bulan Desember 2019 yang mana beberapa pasien datang ke salah satu rumah sakit dengan gejala penyakit yang kurang begitu dikenali.</p>
      </div>
  </div>
</div>
<div class="data">
  <div class="isidata">
      <div class="indo">
          <div id="talkbubble2">
              <h2>Data Covid-19 di Indonesia</h2><br>
              <p style="font-size: 16px;">Update terakhir: 15 Januari 2021</p>
              <p style="font-size: 16px;">Sumber: <a class="link" href="https://covid19.go.id/">covid19.go.id</a></p>
          </div>
          <div id="talkbubble">
              <p>Positif</p>
              <span class="count">882418</span>
          </div>
          <div id="talkbubble">
              <p>Sembuh</p>
              <span class="count">718696</span>
          </div>
          <div id="talkbubble">
              <p>Meninggal</p>
              <span class="count">25484</span>
          </div>
      </div>
  </div>
</div>
<div class="gejala">
  <h1 style="padding-top: 100px;"><a style="color: rgb(167, 0, 0); font-size: 60px;">Covid-19</a> Symptoms</h1><br>
  <p class="anda">Anda perlu mengenal gejala-gejala Covid-19 sejak awal agar tidak membahayakan orang di sekitarmu.</p>
  <div class="isigejala">
      <div id="slideshow">
          <div class="aa">
              <section>
                  <div class="gjl">
                      <img src="https://vectorified.com/images/flu-icon-31.png" style="border: 10px white; border-style: solid; border-radius: 50%;">
                      <br><br><h2>Demam</h2><br>
                      <p>Demam merupakan adalah salah satu gejala awal Covid-19 yang mana penderita memiliki suhu tubuh 38 derajat ke atas.</p>
                  </div>
              </section>
              <section>
                  <div class="gjl">
                      <img src="https://image.flaticon.com/icons/png/512/2660/2660009.png" style="background-color: rgb(167, 0, 0); border: 10px white; border-style: solid; border-radius: 50%;">
                      <br><br><h2>Batuk</h2><br>
                      <p>Batuk secara terus menerus menandakan adanya infeksi di paru-paru yang bisa saja disebabkan oleh virus Corona.</p>
                  </div>
              </section>
              <section>
                  <div class="gjl">
                      <img src="https://cdn.pixabay.com/photo/2016/12/16/07/43/headache-1910710_960_720.png">
                      <br><br><h2>Sakit Kepala</h2><br>
                      <p>Biasanya demam yang mana merupakan salah satu gejala Covid-19 dapat disertai dengan sakit kepala.</p>
                  </div>
              </section>
              <section>
                  <div class="gjl">
                      <img src="https://image.winudf.com/v2/image/Y29tLmFuZHJvbW8uZGV2NTk0NjczLmFwcDgxMDU4MF9pY29uXzE1MjkxMzAxODBfMDUz/icon.png?w=170&fakeurl=1" style="border: 10px white; border-style: solid; border-radius: 50%;">
                      <br><br><h2>Sakit Tenggorokan</h2><br>
                      <p>Seringnya batuk-batuk dapat menyebabkan radang serta rasa nyeri pada tenggorokan akibat infeksi virus Corona.</p>
                  </div>
              </section>
              <section>
                  <div class="gjl">
                      <img src="https://cdn.idntimes.com/content-images/post/20200108/1-2-0e1386ef9e10c8213e59408a660b715d.jpg" style="background-color: rgb(167, 0, 0); border: 10px white; border-style: solid; border-radius: 50%;">
                      <br><br><h2>Mudah Lemas</h2><br>
                      <p>Virus Corona dapat menyebar ke seluruh tubuh yang mana akan menguras energi dalam tubuh manusia sehingga dapat membuat cepat lemas.</p>
                  </div>
              </section>
              <section>
                  <div class="gjl">
                      <img src="https://deteksicorona.slemankab.go.id/img/7.png" style="background-color: rgb(167, 0, 0); border: 10px white; border-style: solid; border-radius: 50%;">
                      <br><br><h2>Sesak Nafas</h2><br>
                      <p>Dengan adanya virus Corona yang berkembang dengan cepat di paru-paru, dapat menyebabkan penderita akan merasakan sesak nafas.</p>
                  </div>
              </section>
          </div>
      </div>
  </div>
</div>

<div class="cegah">
  <div class="isicegah">
      <div class="column" style="padding-top: 90px;">
          <h1>How to Prevent <a style="color: rgb(167, 0, 0); font-size: 48px;">Covid-19</a> ?</h1><br><br><br>
          <p>Agar terhindar dari Covid-19, Anda dapat melakukan:</p><br>
          <p style="font-size: 18px; line-height: 30px;">Mencuci tangan, menerapkan social distancing, sanitasi, memakai masker, berolahraga, dan makan makanan sehat.</p>
      </div>
      <div class="column">
          <img src="https://www.caesars.com/content/dam/empire/health-and-safety/icon-health-safety-handwashing-red.png">
          <img src="https://www.caesars.com/content/dam/empire/health-and-safety/icon-health-safety-6ftdistance-red.png">
          <img src="https://www.caesars.com/content/dam/empire/health-and-safety/icon-health-safety-disinfect-red.png">
          <img src="https://www.caesars.com/content/dam/empire/health-and-safety/icon-health-safety-mask-red.png">
          <img src="https://www.pinclipart.com/picdir/big/35-352304_fda-weights-clip-art-weight-weights-icon-png.png" style="filter: brightness(70%);">
          <img src="https://i.pinimg.com/originals/55/ab/71/55ab71f2b31b37395099238d5647b4aa.png" style="filter: brightness(50%);">
      </div>
  </div>
</div>

{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="icon" type="image" href="{% static 'mailogo.png' %}">
  <link rel="stylesheet" href="/static/css/style.css?{% now 'U' %}">
  <link rel="stylesheet" href="/static/css/responsive.css?{% now 'U' %}">
  <script src='https://kit.fontawesome.com/a076d05399.js'></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  {% block meta %}
  {% endblock meta %}
</head>
<body>
  <nav class="navbar">
    <div class="content">
      <div class="logo">
        <a class="logo" href="{% url 'main:home' %}">BOU<a class="red" href="{% url 'main:home' %}" style="font-size: 26px; color: rgb(167, 0, 0);">VID</a></a>
      </div>
      <ul class="menu-list">
        <div class="icon cancel-btn">
          <i class="fas fa-times"></i>
        </div>
        <li><a href="{% url 'berita:home' %}">Berita</a></li>
        <li><a href="#">Q&A</a></li>
        <li><a href="{% url 'main:logout' %}">Log Out</a></li>
        <li><a id="tema" href="#">Light theme</a></li>
        <li><a><div id="MyClockDisplay" class="clock" onload="showTime()"></div></a></li>
      </ul>
      <div class="icon menu-btn">
        <i class="fas fa-bars"></i>
      </div>
    </div>
  </nav>
  <a id="button"></a>

  {% block content %}
  {% endblock content %}
  
         <div class="footer">
            <div class="kontak">
              <h3>You can contact me via :</h3>
              <div class="parent-card2">
                <div class="isikontak">
                  <a href="mailto:ryandirgaaidilhakim@gmail.com?subject=subject&cc=cc@example.com"><img src="https://cdn0.iconfinder.com/data/icons/material-circle-apps/512/icon-email-material-design-512.png"></a>
                </div>
                <div class="isikontak">
                  <a href="https://wa.me/6281287364751"><img src="https://seeklogo.com/images/W/whatsapp-icon-logo-BDC0A8063B-seeklogo.com.png"></a>
                </div>
                <div class="isikontak">
                  <a href="http://line.me/ti/p/~ryandirgaa"><img src="https://seeklogo.com/images/L/line-messenger-logo-F9E667D0A2-seeklogo.com.png"></a>
                </div>
                <div class="isikontak">
                  <a href="https://t.me/ryandirgaa"><img src="https://icons-for-free.com/iconfiles/png/512/media+social+telegram+icon-1320193121598222952.png"></a>
                </div>
              </div>
            </div>
            <hr style="border-color: rgb(167, 0, 0);">
            <p><span>&#169; 2021 BOUVID. All rights reserved</span></p>
          </div>

          <script>
            const body = document.querySelector("body");
            const navbar = document.querySelector(".navbar");
            const menuBtn = document.querySelector(".menu-btn");
            const cancelBtn = document.querySelector(".cancel-btn");
        
            menuBtn.onclick = ()=>{
              navbar.classList.add("show");
              menuBtn.classList.add("hide");
              body.classList.add("disabled");
            }
            cancelBtn.onclick = ()=>{
              body.classList.remove("disabled");
              navbar.classList.remove("show");
              menuBtn.classList.remove("hide");
            }
            window.onscroll = ()=>{
              this.scrollY > 20 ? navbar.classList.add("sticky") : navbar.classList.remove("sticky");
            }
        </script>
        <script>
            var btn = $('#button');

            $(window).scroll(function() {
                if ($(window).scrollTop() > 300) {
                    btn.addClass('show');
                } else {
                    btn.removeClass('show');
                }
            });

            btn.on('click', function(e) {
                e.preventDefault();
                $('html, body').animate({scrollTop:0}, '300');
            });
        </script>
        <script>
          function showTime(){
              var date = new Date();
              var h = date.getHours(); // 0 - 23
              var m = date.getMinutes(); // 0 - 59
              var s = date.getSeconds(); // 0 - 59
              var session = "AM";
              
              if(h == 0){
                  h = 12;
              }
              
              if(h > 12){
                  h = h - 12;
                  session = "PM";
              }
              
              h = (h < 10) ? "0" + h : h;
              m = (m < 10) ? "0" + m : m;
              s = (s < 10) ? "0" + s : s;
              
              var time = h + ":" + m + ":" + s + " " + session;
              document.getElementById("MyClockDisplay").innerText = time;
              document.getElementById("MyClockDisplay").textContent = time;
              
              setTimeout(showTime, 1000);
          }
          showTime();
        </script>
        <script>
            $('.count').each(function () {
                $(this).prop('Counter',0).animate({
                    Counter: $(this).text()
                }, {
                    duration: 8000,
                    easing: 'swing',
                    step: function (now) {
                        $(this).text(Math.ceil(now));
                    }
                });
            });
        </script>
        <script>
            $(document).ready(function() {
                var clicked = false;

            $('#tema').on('click', function() {
                if(clicked){
                    $('.navbar').css('background', 'black');
                    $('.icon').css('color', 'white');
                    $('.menu-list li a').css('color', '#FFFFFF');
                    $('.navbar .menu-list').css('background', 'black');
                    $('.logo').css('color', '#FFFFFF');
                    $('.welcome').css('background-color', '#000000');
                    $('.welc').css('color', '#FFFFFF');
                    $('.overlay').css('color', '#FFFFFF');
                    $('.what').css('background-color', '#000000');
                    $('.what h1').css('color', '#FFFFFF');
                    $('.isiwhat').css('color', '#FFFFFF');
                    $('.logo2').css('color', '#FFFFFF');
                    $('.klik').css('color', '#FFFFFF');
                    $('.data').css('background-color', '#000000');
                    $('.gejala').css('background-color', '#000000');
                    // $('.data h1').css('color', '#FFFFFF');
                    // $('.isidata').css('color', '#FFFFFF');
                    // $('.link').css('color', '#FFFFFF');
                    $('.gejala h1').css('color', '#FFFFFF');
                    $('.gjl').css('color', '#FFFFFF');
                    $('.anda').css('color', '#FFFFFF');
                    $('.cegah').css('background-color', '#000000');
                    $('.column h1').css('color', '#FFFFFF');
                    $('.column p').css('color', '#FFFFFF');
                    $('.container').css('background', 'black');
                    $('.container').css('color', '#FFFFFF');
                    $('input').css('border-style', 'none');
                    $('textarea').css('border-style', 'none');
                    $('.button').css('color', '#FFFFFF');
                    $('.button').css('border-style', 'solid');
                    $('.span').css('color', 'rgb(255, 167, 167)');
                    $('.tambah').css('color', '#FFFFFF');
                    $('.back').css('color', '#FFFFFF');
                    $('.footer').css('background-color', 'rgb(10, 10, 10)');
                    $('.footer').css('color', '#FFFFFF');
                    $('#tema').css('color', '#FFFFFF');
                    $('#tema').text('Light theme');
                    clicked = false;
                }else{
                    $('.navbar').css('background', 'rgb(209, 209, 209)');
                    $('.icon').css('color', 'black');
                    $('.menu-list li a').css('color', '#000000');
                    $('.navbar .menu-list').css('background', 'rgb(209, 209, 209)');
                    $('.logo').css('color', '#000000');
                    $('.welcome').css('background-color', 'rgb(209, 209, 209)');
                    $('.welc').css('color', '#000000');
                    $('.overlay').css('color', '#000000');
                    $('.what').css('background-color', 'rgb(209, 209, 209)');
                    $('.what h1').css('color', '#000000');
                    $('.isiwhat').css('color', '#000000');
                    $('.logo2').css('color', '#000000');
                    $('.klik').css('color', '#000000');
                    // $('.data').css('background-color', 'rgb(209, 209, 209)');
                    // $('.data h1').css('color', '#000000');
                    // $('.isidata').css('color', '#000000');
                    // $('.link').css('color', '#000000');
                    $('.gejala').css('background-color', 'rgb(209, 209, 209)');
                    $('.gejala h1').css('color', '#000000');
                    $('.gjl').css('color', '#000000');
                    $('.anda').css('color', '#000000');
                    $('.cegah').css('background-color', 'rgb(209, 209, 209)');
                    $('.column h1').css('color', '#000000');
                    $('.column p').css('color', '#000000');
                    $('.container').css('background', 'rgb(209, 209, 209)');
                    $('.container').css('color', '#000000');
                    $('input').css('border-style', 'solid');
                    $('textarea').css('border-style', 'solid');
                    $('.button').css('color', '#000000');
                    $('.span').css('color', '#000000');
                    $('.tambah').css('color', '#000000');
                    $('.back').css('color', '#000000');
                    $('.footer').css('background-color', 'rgb(204, 204, 204)');
                    $('.footer').css('color', '#000000');
                    $('#tema').css('color', '#FFFFFF');
                    $('#tema').text('Dark theme');
                    clicked = true;
                };
                return false;
            });
            });

        </script>
</body>

</html>